### ISSUE TITLE
Parebrick run

### ISSUE THREAD

**Issue by Sirbius** [ctlab/parallel-rearrangements#4]
Hi there,

I have around 160 bacterial genome to compare and I would like to run Parebrick.
I've already run SibeliaZ to get the following commands:

`sibeliaz -k 15 -n -t 96 ../Fasta-simplified/*.fasta`
`maf2synteny -s fine.txt -b 1000 blocks_coords.gff`
`maf2synteny -s fine.txt -b 5000 blocks_coords.gff`

I already have the pangenome performed with roary and the core genome alignment from which I got the phylo tree with RaxML.
Can I use this as a tree? 
How can I avoid to run Panacota, which is unbelievable unfriendly?
Thank you,
Silvia

**Comment by oxygen311** [comment]
Hello Silvia,

If I got it right, you can use blocks constructed with sibeliaz with passing `-b` parameter and tree constructed with RaxML with `-t`. This is all required input for parebrick.

Panacota is just another way to construct core-genome and phylo tree.

**Comment by Sirbius** [comment]
Dear oxygen, 
Thank you for your reply. 

Yes, that's exacly what I did:
`parebrick -t ../roary/RAxML_bestTree.core-tree -b 5000/`

So if this is right, I just need to fix this problem with the IDs:

`Cleaning output folder
[2022-02-22 09:54:07,822] INFO - <Running module: Preprocess Data>
--------------------------------------------------------------------------------
[2022-02-22 09:54:08,026] INFO - Converting block coords to infercars format
--------------------------------------------------------------------------------
[2022-02-22 09:54:10,163] INFO - <Module finished: Preprocess Data>, elapsed 2.340909004211426 seconds


[2022-02-22 09:54:10,164] INFO - <Running module: Parsers and check strains>
--------------------------------------------------------------------------------
[2022-02-22 09:54:11,145] WARNING - No unique one-copy blocks found. Balanced rearrangements will not be called
[2022-02-22 09:54:11,190] INFO - Blocks count: 145
[2022-02-22 09:54:11,191] INFO - Unique one-copy blocks count: 0
[2022-02-22 09:54:13,130] INFO - Mean block coverage: 25.67279078034808 %
[2022-02-22 09:54:13,132] INFO - Mean common one-copy blocks coverage: 0 %
[2022-02-22 09:54:13,132] INFO - Mean 80 % rate one-copy blocks coverage: 0 %
[2022-02-22 09:54:13,153] INFO - Trying to root tree by first child of root
[2022-02-22 09:54:13,162] INFO - Children of root: [Tree node '' (0x7fab11a685c), Tree node 'Psa_JA12' (0x7fac51a7ccc), Tree node 'Psa_105743' (0x7fac51a7cd3)]
[2022-02-22 09:54:13,222] INFO - Strains in blocks file count: 3146
[2022-02-22 09:54:13,223] INFO - Strains in tree leafs count: 153
[2022-02-22 09:54:13,223] INFO - Intersected strains count: 0
[2022-02-22 09:54:13,224] ERROR - Tree genomes: {tree_genomes}
[2022-02-22 09:54:13,224] ERROR - Blocks genomes: {block_genomes}
[2022-02-22 09:54:13,225] ERROR - Seems like strains in block files and in tree leafs have different ids, intersection is empty.
Traceback (most recent call last):
  File "/home/silviat/.local/bin/parebrick", line 8, in <module>
    sys.exit(main())
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/main.py", line 371, in main
    parsers_and_stats()
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/utils/decorators.py", line 13, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/main.py", line 191, in parsers_and_stats
    genomes = check_stats_stains(tree_holder, set(genomes), logger)
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/utils/data/stats.py", line 69, in check_stats_stains
    'Seems like strains in block files and in tree leafs have different ids, intersection is empty.')
ValueError: Seems like strains in block files and in tree leafs have different ids, intersection is empty.
`

**Comment by Sirbius** [comment]
Dear oxygen,
Thank you for your reply.

Yes, that's exacly what I did:
parebrick -t ../roary/RAxML_bestTree.core-tree -b 5000/

So if this is right, I just need to fix this problem with the IDs:

Cleaning output folder

[2022-02-22 09:54:07,822] INFO -
[2022-02-22 09:54:08,026] INFO - Converting block coords to infercars format
[2022-02-22 09:54:10,163] INFO - , elapsed 2.340909004211426 seconds
[2022-02-22 09:54:10,164] INFO -
[2022-02-22 09:54:11,145] WARNING - No unique one-copy blocks found. Balanced rearrangements will not be called
[2022-02-22 09:54:11,190] INFO - Blocks count: 145
[2022-02-22 09:54:11,191] INFO - Unique one-copy blocks count: 0
[2022-02-22 09:54:13,130] INFO - Mean block coverage: 25.67279078034808 %
[2022-02-22 09:54:13,132] INFO - Mean common one-copy blocks coverage: 0 %
[2022-02-22 09:54:13,132] INFO - Mean 80 % rate one-copy blocks coverage: 0 %
[2022-02-22 09:54:13,153] INFO - Trying to root tree by first child of root
[2022-02-22 09:54:13,162] INFO - Children of root: [Tree node '' (0x7fab11a685c), Tree node 'Psa_JA12' (0x7fac51a7ccc), Tree node 'Psa_105743' (0x7fac51a7cd3)]
[2022-02-22 09:54:13,222] INFO - Strains in blocks file count: 3146
[2022-02-22 09:54:13,223] INFO - Strains in tree leafs count: 153
[2022-02-22 09:54:13,223] INFO - Intersected strains count: 0
[2022-02-22 09:54:13,224] ERROR - Tree genomes: {tree_genomes}
[2022-02-22 09:54:13,224] ERROR - Blocks genomes: {block_genomes}
[2022-02-22 09:54:13,225] ERROR - Seems like strains in block files and in tree leafs have different ids, intersection is empty.
Traceback (most recent call last):
File "/home/silviat/.local/bin/parebrick", line 8, in
sys.exit(main())
File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/main.py", line 371, in main
parsers_and_stats()
File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/utils/decorators.py", line 13, in wrapper
return_value = func(*args, **kwargs)
File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/main.py", line 191, in parsers_and_stats
genomes = check_stats_stains(tree_holder, set(genomes), logger)
File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/utils/data/stats.py", line 69, in check_stats_stains
'Seems like strains in block files and in tree leafs have different ids, intersection is empty.')
ValueError: Seems like strains in block files and in tree leafs have different ids, intersection is empty.

Of course the strains in block files have the _numerofblock which is different from the strain name in the tree leaf.
Do you have any idea how to fix this??

**Comment by Sirbius** [comment]
This is what happens if I use a different tree: 
`parebrick -t ../MLST/RAxML_bestTree.MLST -b 5000/
`
Traceback (most recent call last):
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/tree/tree_holder.py", line 108, in assign_colorset_feature
    child1, child2 = v.children
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silviat/.local/bin/parebrick", line 8, in <module>
    sys.exit(main())
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/main.py", line 379, in main
    unbalanced_rearrangements_stats_and_clustering()
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/utils/decorators.py", line 13, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/main.py", line 266, in unbalanced_rearrangements_stats_and_clustering
    ub_stats = get_characters_stats_unbalanced(blocks, ub_characters, tree_holder)
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/characters/unbalanced.py", line 13, in get_characters_stats_unbalanced
    tree_holder.count_innovations_fitch(genome_colors)
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/tree/tree_holder.py", line 137, in count_innovations_fitch
    assign_colorset_feature(root)
  File "/home/silviat/.local/lib/python3.6/site-packages/parebrick/tree/tree_holder.py", line 111, in assign_colorset_feature
    raise ValueError('Tree must me binary')
ValueError: Tree must me binary

:(

**Comment by oxygen311** [comment]
It looks like there is some problem with tree format, it is expected to be binary in most nodes.

Could you share your data for trying to fix this bug?

**Comment by Sirbius** [comment]
This second one yes, it mentions some binary. But what is meant with binary in this case?

Sure I can share it:

The core tree:
https://drive.google.com/file/d/1o5ObvWMYCXyyMOjbt3vNL73DYgVergS3/view?usp=sharing
The second tree that gave the binary error was build on the alignment of 7 genes and probably not the right one, righ?

The block coords:
https://drive.google.com/file/d/16J64pElxt69qPxpAbJ7XjDicttFUdVNT/view?usp=sharing

And the fine.txt was created as mentioned in the parebrick manual:
30 150
100 500
500 1500

Tell me if you need anything else!
Thanks!

**Comment by oxygen311** [comment]
Unfortunately, I can't run peribrick to test your data with only `blocks_coords.txt` file, I need to have all maf2synteny output folder.

But I've checked your tree, it seems alright and supposed to work if nodes are not pruned due to lack of strains in blocks data. You can send me tool log to check this fact.

<br>

> This second one yes, it mentions some binary. But what is meant with binary in this case?

This line `child1, child2 = v.children` is supposing that node `v` has 2 children.

**Comment by Sirbius** [comment]
Here all the content of the 5000/ folder and the run.log file :)
[run.log](https://github.com/ctlab/parallel-rearrangements/files/8134609/run.log)
[coverage_report.txt](https://github.com/ctlab/parallel-rearrangements/files/8134610/coverage_report.txt)
[blocks_coords.txt](https://github.com/ctlab/parallel-rearrangements/files/8134611/blocks_coords.txt)
[genomes_permutations.txt](https://github.com/ctlab/parallel-rearrangements/files/8134612/genomes_permutations.txt)

**Comment by oxygen311** [comment]
With this data, problem is still in empty intersection:
> [2022-02-24 18:42:50,590] ERROR - Seems like strains in block files and in tree leafs have different ids, intersection is empty.

E.g. there is genome Psa_ICMP19099_296 in blocks, but it's not presented in tree. And there is genome Psa_Guizhou_G25 in tree which is not presented in blocks data.

**Comment by Sirbius** [comment]
This is really strange since the Fasta-folder I used to run either sibelia or roary was the same!
I will check better and come back to you next week,
In the meantime, thanks for your efforts!
Silvia

**Comment by oxygen311** [comment]
You are welcome!

In case of facing issues with data, feel free to ask them here.

**Comment by Sirbius** [comment]
Hi there,

I checked the tree and Psa_ICMP19099 is there:
![Screenshot at 2022-03-01 14-29-36](https://user-images.githubusercontent.com/44462713/156179350-26b6f512-985d-4454-a020-96f3397da050.png)

And there are four lines in the block coordinates file related to Psa_Guizhou_25.
![Screenshot at 2022-03-02 09-45-16](https://user-images.githubusercontent.com/44462713/156326922-9a3d6139-9063-4fc3-a57c-b02cc7d89653.png)

Of course there is no Psa_ICMP19099_296 (_296), since this is added in the block file.
So I really do not know how to proceed...

**Comment by oxygen311** [comment]
> Of course there is no Psa_ICMP19099_296 (_296), since this is added in the block file. So I really do not know how to proceed...

Hello,

Labels in tree and blocks for strains are supposed to be **the same**. Tool does not know that `Psa_ICMP19099_296` and `Psa_ICMP19099` are actually the same strain.

I think you can process your data to fix it.

**Comment by Sirbius** [comment]
Sure but that would be true for any other strain in the block file!!

ok so I should modify the strain name in the block file leaving only Psa_ICMP19099 ...?

**Comment by oxygen311** [comment]
> Sure but that would be true for any other strain in the block file!!
> 
> ok so I should modify the strain name in the block file leaving only Psa_ICMP19099 ...?

It's better to do it with a tree. Blocks contain three files with info.

**Comment by Sirbius** [comment]
And which on the main block numbers should I place in the tree?? If one strain has multiple block numbers, like Guizhou 25 that I showed you before?
This doesn't make much sense. How do you usually do? How does this tool normally work with names?

**Comment by oxygen311** [comment]
> And which on the main block numbers should I place in the tree??
> This doesn't make much sense. How do you usually do? How does this tool normally work with names?

Then update `genomes_permutations.txt` and `genomes_permutations.txt` files.

Usually, I don't have such problems because of using same data with same labels for both blocks and tree construction.

**Comment by Sirbius** [comment]
There are more than 1000 lines in both genomes_permutations.txt and coverage_report, if these are the files you mean.
And there are coordinates related to many block numbers per each strain, so I do not see/understand how this strain name modification could be done without loosing the block coordinates.

I guess that the original script should just recognize the prefix name of the strain and thus, take whatever is before the block number _blocknumber as strain name, which would then be the same in the phylogenetic tree.
I do not see how you could compare the date if you use same lables for both blocks and tree.

**Comment by oxygen311** [comment]
I checked your data and didn't get why strains have different suffixes, for example, strain Psa_Saga2 have multiple mentions in block as `Psa_Saga2_24`, `Psa_Saga2_91`, `Psa_Saga2_2`, `Psa_Saga2_501` and `Psa_Saga2_101`.

PaReBrick is meant to be used with the same data for strains on tree and blocks. It can't take into account different versions/dates of strains data.

**Comment by Sirbius** [comment]
That's the point I was trying to explain, I'm sorry if I was not clear! 
Could that be related to the fact that the contings if the Fasta genome files are called in an increasing way, like this:
>Psa_Saga2_1
>Psa_Saga2_2
>Psa_Saga2_3... and so on.
Should I use >Psa_Saga2 for all of them?

**Comment by oxygen311** [comment]
> That's the point I was trying to explain, I'm sorry if I was not clear! Could that be related to the fact that the contings if the Fasta genome files are called in an increasing way, like this:

Unfountnatly, current version of PaReBrick can't operate contig-level assemblies, only whole genomes. We have plans to extend this tool for partly assembled genomes since it's most common type of data. But for now, this is still a restriction :(

**Comment by Sirbius** [comment]
Oh, ok. That's the problem! I have only 10 complete assembly..I'll find another way. 
Thank you very much!

**Comment by oxygen311** [comment]
Thank you for your time!

I'll let you know when contig feature will be added.
